name: PR Check

on:
  pull_request:
    branches: main

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      did-frontend-change: ${{ contains(steps.set-labels.outputs.all-labels, 'frontend') }}
      did-backend-change: ${{ contains(steps.set-labels.outputs.all-labels, 'backend') }}
    steps:
      - uses: actions/labeler@v5
        id: 'set-labels'

  frontend_check:
    needs: labeler
    if: needs.labeler.outputs.did-frontend-change == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Run tests
        run: npm run test
      - name: Build
        run: npm run build

  backend_check:
    needs: labeler
    if: needs.labeler.outputs.did-backend-change == 'true'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run lint
      - name: Run tests
        run: npm run test
